spring:
    application:
        port: 8081
        name: rabbitmq-springboot
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest
        publisher-confirms: true
#        virtual-host: /
#         采用手动应答
        listener:
            acknowledge-mode: manual